### ISSUE TITLE
Build out abstract release instructions

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#21]
Begin building out the abstract (i.e. non-mechanical) aspects of the release process. This should include sufficient descriptions of release streams, an ideal case procedure, and identification of artifact dependencies. A later task will begin to tackle implementation mechanics.

**Comment by DavidRies** [comment]
Here's a first/rough draft: https://github.com/CISecurity/oval-governance-update/blob/master/process_artifacts/release_instructions.md

**Comment by david-waltermire-nist** [comment]
I still prefer 3 implementations for transition to the stable "release" branch. This gives a greater level of assurance than two implementations. For example, a feature might be created through a collaboration between two organizations. They both implement based on their shared understanding. A third implementation can then bring an independent view. FWUW, while binary relationships are easy to form, trinary relationships are less likely and harder to develop "group think" around.

**Comment by adammontville** [comment]
@DavidRies and/or @wmunyan may have additional comments or corrections to this. Essentially, none of us had a strong opinion about preferring 2 vs. 3 implementations for transition to the stable branch. We did, however, note that in some cases, finding 3 implementations may prove to be difficult, which will force some vendors to explicitly support the development branch. Still, no extreme objection to having the requirement be 3 vs. 2.

If others have thoughts on any of this, please reply.

**Comment by DavidRies** [comment]
I am fine with 2 or 3. 

In some cases, getting 3 implementations may prove challenging. Some of the OVAL engine developers who are most active in this community work on engines with a limited mandate (i.e. to support a specific set of content and/or platforms and/or use cases). So, for example, it might be tough to get implementations of new tests for platforms like Cisco ASA or Mac OS X.

I'm fine going with 3 and dealing with this issue if/when it comes up.

**Comment by david-waltermire-nist** [comment]
Good. I believe 3 is considerably better.

In cases where getting 3 implementations is challenging, I would guess we are dealing with a feature that is on the edge of what is needed by the larger community. If this is the case, it may be better to relegate the feature to the extension branch anyways. Also, there is nothing that stops platforms for which there are only one or two implementations from adopting extensions that make sense for their platform. This doesn't mean that those extension make sense from the broader perspective of the OVAL community as a whole.

**Comment by wmunyan** [comment]
I would also be hopeful that 3 implementations would foster some more communication and collaboration between members of the OVAL community as a whole.  Those folks who are proposing the schema should be reaching out to the broad OVAL community for feedback, potential implementations, and consensus.  Maybe that's my own personal OVAL utopia...

**Comment by adammontville** [comment]
Rendered moot by the point system idea. See #33
