### ISSUE TITLE
Build out abstract "issue" guidelines

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#28]
Such guidelines should include guidance on creating and responding to issues (i.e. issue disposition). A later task will involve the mechanics of using GitHub to create and manage these issues.

**Comment by DavidRies** [comment]
Please see draft here: https://github.com/CISecurity/oval-governance-update/blob/master/process_artifacts/issue_instructions.md

**Comment by adammontville** [comment]
Thanks for posting this, David. Is the intent of this draft to characterize the attributes we desire in our issues before getting into the GitHub mechanics of it?

**Comment by DavidRies** [comment]
Yes.

**Comment by adammontville** [comment]
I'm just realizing that, now that I moved your two issues to "in progress" (sigh). Thanks for your quick response.

**Comment by DavidRies** [comment]
There was a discussion on the call around the usefulness of priorities. I am going to remove them for now. We can certainly add them back later on.

**Comment by wmunyan** [comment]
David, I agree with the removal of priorities for now.  As you said, if we need them later, we can add them.  I think for now folks are going to focus efforts on those issues/proposals that meet their needs, and can add value to their respective implementations.
