### ISSUE TITLE
Draft overarching narrative

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#40]
We need to draft an overarching narrative to the language development process that ties the graphical depictions and process artifacts together.

**Comment by adammontville** [comment]
I'm thinking about starting by updating the [README.md](https://github.com/CISecurity/oval-governance-update/blob/master/README.md), so that it matches our latest thinking - but, I'll likely start this the week after next.

**Comment by adammontville** [comment]
See [README.md](https://github.com/CISecurity/oval-governance-update/blob/master/README.md) for the update. I added an overview section describing the ultimate intent of, and major roles to be played in, the process. I made some minor changes to the text that already existed.

**Comment by DavidRies** [comment]
This looks really great. I have a few minor notes for your consideration:

- Language Development Process Goals: 
	- 5.vii may be a typo… should it be outdented to be #6? 
- Process : Overview: Roles: 
	- Leadership Board: add that they are responsible for selected the Official Release(s)
	- Community: responsible for maintaining OVAL and these governance processes by creating issues, reviewing issues, creating change proposals, collaborating on change proposals, reviewing change proposals and generally contributing to this consensus-driven process.
- Process Details: Create GitHub Issue
	- Change first sentence to "Anyone can create a GitHub Issue describing a problem with or opportunity to improve the OVAL Language.”
- Release and Logistical Support
	- Change 2nd sentence to: These accepted proposals are released into the Development release stream. Once they have sufficient implementation support, they are moved to the Stable release stream on the next release date. Proposals that are not accepted may be released to the Extensions release stream. See the release instructions for additional detail.

**Comment by adammontville** [comment]
Thanks, David, for your feedback. Let's go through it during today's meeting.

**Comment by adammontville** [comment]
Done.
