### ISSUE TITLE
Complete the page "Release Process"

### ISSUE THREAD

**Issue by zport** [CISecurity/oval-governance-update#71]
Add details on the [Release Process](https://github.com/OVAL-Community/OVAL/blob/master/guidelines/proposal-process/release-process.rst) page.

Detailing this page should also address and solve issue #22.

**Comment by adammontville** [comment]
Finally taking a look at this. The release process page information references the concept of a Qualifying Implementation. I'm inclined to create a new page for that information also contained in the `proposal-process` directory (basically a peer to the release process page). Alternatively, I can describe the concept within the release process page.

Does anyone have a strong preference toward the latter? If so, please opine.

**Comment by adammontville** [comment]
Not done yet, but have a start that should probably be reviewed before going to much further.

**Comment by zport** [comment]
Please update the line:
"When a Qualifying Implementation qualifies for multiple scores, only the highest single score will be counted."
to enhance clarity.
