### ISSUE TITLE
Consider releasing for different stakeholder needs

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#9]
There exists a continuum of needs for automation content that demand various degrees of rigor when releasing and updating the OVAL language, due to widely deployed (possibly slow to update) components, software lifecycles, and other factors. We should consider how we can craft an OVAL language development process capable of satisfying the wide range of stakeholder needs. 

Perhaps a "stable" branch and an "experimental" branch, or, we could do something with versioning conventions (i.e. similar to Linux kernel versioning...odd number releases are experimental or "developer" releases, even numbered releases are stable), or something else.

**Comment by wmunyan** [comment]
Could this have been addressed [here](http://ovalproject.github.io/documentation/policy/versioning/)?  Might be worth seeing if this versioning policy could be incorporated into the process.

**Comment by adammontville** [comment]
Thanks for that link, Bill. We should look at that.

**Comment by adammontville** [comment]
From a conversation summary provided by David Ries on ways we might be able to address qualtiy concerns the "default accept" approach appears to raise:

* Concerned parties can become Area Supervisors and/or engage in the process as a Community Member to help ensure quality
* To the extent we have invested, authoritative Area Supervisors, we can trust them to ensure quality in their Areas (e.g. if Martin@RedHat is the Linux Schema Area Supervisor, it’s unclear what a further quality review by the Board would add)
* Quality criteria should be clearly documented in the PR Instructions and Design Principles
* Bad ideas can be commented on and potentially abandoned at the Issue stage
* Fundamentally low-quality (or “bad”) Proposals can be quashed via Objections based on the PR Instructions and Design Principles
* Sub-optimal Proposals can be fixed in collaboration with the First Proposal author
* Sub-optimal Proposals can be avoided by creating and advocating for a more optimal Alternative Proposal
* Low-quality Proposals that make it through the process can be amended or removed via the Process (e.g. create a new ticket, make a Proposal to fix/remove, etc.)

**Comment by adammontville** [comment]
Additional information from David Ries (different e-mail):

*Based on today’s discussion, I have an idea for how we might organize the various “development streams” (is there a real word for this?) into four categories:*

* *Extensions: Proposals that are not accepted, but that the Proposal author or supervisor wants to make available as an unofficial extension*
* *Development: accepted Proposals that haven’t been released*
* *Release: all accepted Proposals released every 6 months*
* *Official: a Release that the Board decides is “official” each year*

**Comment by adammontville** [comment]
I've updated [release instructions](https://github.com/CISecurity/oval-governance-update/blob/master/process_artifacts/release_instructions.md) to include the four release stream descriptions, and I've started to build out our project to better reflect what we have yet to do (and many of the bullets elsewhere in this thread are accounted for there - see [project](https://github.com/CISecurity/oval-governance-update/projects/1). Changes will be pushed soon.
